- name: Julia Sun
  position: Co-President
  Year: Junior
  majors: Computer Science
  hobbies: getting boba, cooking, watching kdramas, gymnastics
  fun-fact: I hate all condiments except bbq sauce
  bio: Hi! My name is Julia, and I'm currently a third year studying computer science. In my free time, I enjoy doing puzzles, getting boba, and eating yummy food! My fav spots at Cal are tp tea and marugame udon <33 !!
  socials:
    linkedin: https://www.linkedin.com/in/julia-sun-1bb41b21a/
    coffee: https://calendly.com/jsun28/datagood-coffee-chat-julia

- name: Manan Bhargava
  position: Co-President
  Year: Junior
  majors: Computer Science, Data Science, Entrepreneurship & Technology
  hobbies: Photography, Burn Pen Art (calligraphy with a 900 degree F tip on wood), hiking, traveling, and baking
  fun-fact: I'm level 2500 (superstar class maximum) in Wii sports table tennis
  bio: What's up! I'm a junior from the Bay Area and a startup nerd. In my free time, I enjoy photography, doing burn pen art, hiking, and baking. Fun fact I'm a max pro table tennis wii player and am a game pigeon word hunt master! Play me â­ï¸ 
  socials:
    linkedin: https://www.linkedin.com/in/manan-bhargava/
    coffee: https://calendly.com/manan-bhargava/datagood-coffee-chat-manan-bhargava

- name: Jennifer Ly
  position: External VP
  Year: Sophomore
  majors: Computer Science, Data Science
  hobbies: Valorant, WordHunt, collecting stationery, boba, R&B music
  fun-fact: I used to have pet peacocks
  bio: Hello! My name is Jennifer! I am a second-year from Las Vegas, Nevada studying computer science and data science! I serve as DataGood's Executive Vice President! Some of my interests/hobbies include playing video games (Valorant >:D), creating arts & crafts, listening to music, and exploring new food places! Excited to meet everyone! 
  socials:
    linkedin: https://www.linkedin.com/in/jennifertrinhly/
    coffee: https://calendly.com/jennifertrinhly/datagood-coffee-chat-jennifer-ly

- name: Tiffany Dai
  position: VP of Outreach
  Year: Junior
  majors: Economics, Data Science
  hobbies: Cooking, reading, and fashion
  fun-fact: N/A
  bio: Talk to me about all things cooking, reading, and fashion!
  socials:
    linkedin: https://www.linkedin.com/in/tiffany-dai/
    coffee: https://calendly.com/tiffanydai/

- name: Maxmillion Song
  position: VP of Marketing
  Year: Sophomore
  majors: Data Science
  hobbies: piano, singing, watching tiktok, listening to k-pop
  fun-fact: I love to go cafe hopping in my free time, and take aesthetic pictures!
  bio: Hey guys! I go by Max (Maxmillion is way too extra) and I'm a Freshman studying Data Science! I'm from Koreatown, LA. I'm absolutely addicted to TikTok, and I also really love anything K-Pop, Marvel, and Genshin Impact. In my freetime, I love to hang out with fellow ROHP members, perform with DeCadence (best acapella group on campus), go online shopping for clothes and makeup, and check out fun food spots and cafes! My ig is @mmaxsong, feel free to reach out if you want to talk or have any questions!
  socials:
    linkedin: https://www.linkedin.com/in/maxmillion-song-75391824a/
    coffee: https://calendly.com/maxmillionsong/datagood-coffee-chat

- name: Ramisha Kabir
  position: Co-VP of Research
  Year: Junior
  majors: Data Science, Computer Science
  hobbies: gym, travelling and reading in cafes
  fun-fact: I lived in 4 countries last year
  bio: Hey! I'm your co-VP of Research for this year and i'm so excited to be here! I love traveling, nature, reading, watching good shows, hanging out with dogs and tea.
  socials:
    linkedin: https://www.linkedin.com/in/ramisha-kabir-624288160/ 
    coffee: https://calendly.com/ramishakabir/30min

- name: Rose Lee
  position: Co-VP of Research
  Year: Junior
  majors: Data Science & Cognitive Science
  hobbies: Getting Philz, Learning new recipes, Thrifting
  fun-fact: I have damaged or broken every Apple product I own
  socials:
    linkedin: https://www.linkedin.com/in/rose-lee-0492141b5/
    coffee: https://calendly.com/rroselee/datagood 

- name: Riya Singhal
  position: VP of Industry
  Year: Junior
  majors: Computer Science
  hobbies: Painting, Hiking, Listening to Taylor Swift, Calligraphy
  fun-fact: I have a twin sister and love koalas!
  socials:
    linkedin: https://www.linkedin.com/in/riyasinghal-/
    coffee: https://calendly.com/riya-singhal/datagood-coffee-chat-riya-singhal?month=2023-01
 
- name: Kenneth Nguyen
  position: Co-VP of Social
  Year: Junior
  majors: Data Science
  hobbies: Going to the gym, mixing music, or playing pool with friends!
  fun-fact: N/A
  bio: What's up everyone! My name's Kenneth and I'm a third year majoring in data science. In my free time you'll find me at the gym, mixing music, or playing pool with friends! 
  socials:
    linkedin: https://www.linkedin.com/in/kennethnguyen1/
    coffee: https://calendly.com/kennethnguyen/datagood-coffee-chat-kenneth-nguyen

- name: Akash Iyer
  position: Co-VP of Social
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: Hi! Things I enjoy include getting active in the gym, meditating, and playing chess. This year I'm hoping to have enough time to learn guitar. I love talking about a lot of things, from video games to music to data science. 
  socials:
    linkedin: http://linkedin.com/in/akash-v-iyer
    coffee: https://calendly.com/acashiyer/datagood-coffee-chat-akash-iyer-1

- name: Akira Chou
  position: VP of Finance
  Year: Senior
  majors: Data Science & Economics
  hobbies: taking unnecessary naps, folding modular origami, talking with homo sapiens
  fun-fact: I can wiggle my ears, but only when no one is watching
  bio: Hey, I'm a Econ/DS student, expanding my knowledge and aiming to avoid future unemployment. When I'm not rushing to finish an assignment, you'll often find me exploring the grocery store isles, deciding on what to order on snackpass, or pestering my roommates. Don't hesitate to reach out! 
  socials:
    linkedin: https://www.linkedin.com/in/akirachou/
    coffee: https://calendly.com/akirachou/15min

- name: Sinead McCaffery
  position: Webmaster
  Year: Junior
  majors: Computer Science
  hobbies: dancing, traveling, working out, reading, animals, coffee
  fun-fact: I was an Irish dancer for 15 years!
  bio: Hi guys! I'm Sinead, and I'm in currently in charge of the website and other media platforms for Datagood! I love traveling, cooking, dancing, and animals!
  socials:
    linkedin: https://www.linkedin.com/in/sineadmccaffery/
    coffee: https://calendly.com/sineadmccaffery/datagood-coffee-chat-sinead-mccaffery

- name: Elizabeth Zhou
  position: Industry PM
  Year: Senior
  majors: Data Science, MCB
  hobbies: N/A
  fun-fact: N/A
  bio: Besides data science, I'm passionate about biology, teaching, and debate. In my free time, I love to hike and play cooking games :)
  socials:
    linkedin: https://www.linkedin.com/in/elizzhou
    coffee: https://calendly.com/elizzhou/datagood-coffee-chat?month=2023-08

- name: Bianca Poblano
  position: Industry PM
  Year: Senior
  majors: Data Science, Public Health
  hobbies: N/A
  fun-fact: N/A
  bio: My social good interests include health, education, environment. My hobbies are soccer, crotcheting, and making travel itinearies
  socials:
    linkedin: https://www.linkedin.com/in/bianca-isabel-poblano/
    coffee: https://calendly.com/bpoblano/datagood-coffee-chat-bianca

- name: Jack Swenson
  position: Industry PM
  Year: Junior
  majors: Data Science & Economics
  hobbies: Tennis/Chess/Film/Hiking/Watching Youtube/Hip Hop Music
  fun-fact: I can play chess blindfolded
  socials:
    linkedin: https://www.linkedin.com/in/jack-swenson
    coffee: https://calendly.com/jack-swenson/15min?month=2023-01&date=2023-01-23

- name: Will Rathgeb
  position: Industry PM
  Year: Junior
  majors: Data Science, Statistics
  hobbies: N/A
  fun-fact: N/A
  bio: In my free time I like to play tennis and chess. I'm big soccer, tennis, and baseball fan. 
  socials:
    linkedin: https://www.linkedin.com/in/william-rathgeb-537708222/
    coffee: https://calendly.com/willrathgeb/datagood-coffee-chat

- name: Kaan Taner
  position: Industry PM
  Year: Senior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: I like hiking, swiming, and watching movies. I'm an avid traveler and try to squeeze something international in every  year and have recently been getting into more local trips too! Ionic is the best type of column.
  socials:
    linkedin: https://www.linkedin.com/in/kaantaner/
    coffee: https://calendly.com/kaantaner/datagood-coffee-chat-kaan-taner

- name: Shuhan Luo
  position: Industry PM
  Year: Senior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: RSF Fanatic, Boxing&MMA, Videogames (CSGO, Val, League)
  socials:
    linkedin: https://www.linkedin.com/in/shuhan-luo/
    coffee: https://calendly.com/mysterymeat/datagood-coffee-chat-shuhan-luo

- name: Destiny Hursh
  position: Research PM
  Year: Junior
  majors: Data Science, Psychology
  hobbies: N/A
  fun-fact: N/A
  bio: In my free time, which none of us have much of nowadays, I love to watch anything related to true crime. I love to do escape rooms, and go on road trips with my friends. I've also been getting more into yoga and meditation lately. A fun/not so fun fact about me is that I have double jointed elbows. ðŸ‘€
  socials:
    linkedin: https://www.linkedin.com/in/destiny-hursh-27792b194/ 
    coffee: https://calendly.com/destinyhursh/datagood-coffee-chat

- name: Megan Dhingra
  position: Research PM
  Year: Junior
  majors: Data Science, Economics
  hobbies: N/A
  fun-fact: N/A
  bio: I'm from Pleasanton, CA and you can catch me at the RSF climbing the new rock wall or weightlifting. 
  socials:
    linkedin: https://www.linkedin.com/in/megan-dhingra/ 
    coffee: https://calendly.com/megandhingra/datagood-coffee-chat-megan-dhingra

- name: Alaysha Zarate
  position: Research PM
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: Hey all. I love to video game, draw, and travel. I am interested in working for a video game company or nonprofit organization in the future. Fun Fact - I love going to museums :)
  socials:
    linkedin: https://www.linkedin.com/in/alaysha-zarate-3b6740146/
    coffee: https://calendly.com/alayshaz09/datagood-coffee-chat-alaysha?month=2023-08

- name: Aidan Praytor
  position: Research PM
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: I like painting :)
  socials:
    linkedin: https://www.linkedin.com/in/aidanpraytor/ 
    coffee: https://calendly.com/aidanpraytor/15min

- name: Jasmine Ma
  position: Research PM
  Year: Sophomore
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: Hey guys! I'm Jasmine, a research PM for this semester. My hobbies include watching kdramas, listening to Playboi Carti, and sleeping.
  socials:
    linkedin: https://www.linkedin.com/in/jasmine-ma10
    coffee: https://calendly.com/jasminema-1/datagood-coffee-chat-jasmine-ma

- name: Paulina Villasenor
  position: Research PM
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: I love traveling being wined and dined and discovering the intersection between analytics and creative spaces like fashion
  socials:
    linkedin: https://www.linkedin.com/in/paulina-villasenor/
    coffee: https://calendly.com/paulinavillasenor/30min

- name: Aditi Telang
  position: Research PM
  Year: Sophomore
  majors: Computer Science, Business
  hobbies: N/A
  fun-fact: N/A
  bio: Hi! I'm Aditi. I'm a sophomore majoring in CS and business. I worked on an internal project last semester and I'll be research PM this year! I like to paint, try new foods and play tennis. 
  socials:
    linkedin: https://www.linkedin.com/in/adititelang/
    coffee: https://calendly.com/aditi-telang

- name: Yasmin Ho
  position: Research PM
  Year: Junior
  majors: Data Science
  hobbies: N/A
  fun-fact: N/A
  bio: I was born and raised in South Africa! In my free time, I enjoy hiking and trying new restaurants and cafes!
  socials:
    linkedin: https://www.linkedin.com/in/yasmin-ho-112103226/
    coffee: https://calendly.com/yasminho/datagood-coffee-chat-yasmin
